Update patch set 1
Patch Set 1: Code-Review-1

> Patch Set 1:
> 
> (2 comments)
> 
> > Patch Set 1: Code-Review-1
> > 
> > (2 comments)
> > 
> > Inline comments on the first java file are applicable to most of the other files.
> > 
> > Can we remove the powermockito dependency on one of the earlier branches, and then on stable-3.0 just remove the explicit mockito dependency?
> 
> Honestly, it doesn't create problems before v3.0 and this plugin is pretty much stable.
> However, let's see what Matthew (the author) thinks :-)
> 
> I am not against the idea of getting rid of powermockito from the beginning, because it was added by mistake IMHO.

I need to go back and have a deeper look to see what the reason I needed PowerMock in the first place. 

Regardless, I am not able to even execute the test target on this patch as is. I am seeing the following.

bazel test slack-integration_tests
  Starting local Bazel server and connecting to it...
  DEBUG: Rule 'com_googlesource_gerrit_bazlets' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1558570382 +0900"
  ERROR: error loading package '': Unable to load file '//:external_plugin_deps.bzl': file doesn't exist
  ERROR: error loading package '': Unable to load file '//:external_plugin_deps.bzl': file doesn't exist
  INFO: Elapsed time: 4.072s
  INFO: 0 processes.
  FAILED: Build did NOT complete successfully (0 packages loaded)
  FAILED: Build did NOT complete successfully (0 packages loaded)

Patch-set: 1
Reviewer: Gerrit User 1015822 <1015822@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Code-Review=-1