Update patch set 2
Patch Set 2:

In-tree tests failing locally upon [1]:

[1] (...)
Caused by: java.lang.NoClassDefFoundError: org/mockito/cglib/proxy/MethodInterceptor
        at org.powermock.api.mockito.internal.mockmaker.PowerMockMaker.<init>(PowerMockMaker.java:42)

-Also before this change. Not enough time left for myself to fix this today though.

Patch-set: 2
Reviewer: Gerrit User 1012732 <1012732@173816e5-2b9a-37c3-8a2e-48639d4f1153>